/*******************************************************************************
* \file             main.c
* 
* \version          1.10
*
* \brief            Demo interrupt mode of Mft Icu module, a wave generated by 
*                   a GPIO is measured
*
********************************************************************************
* \copyright
* Copyright 2016, Cypress Semiconductor Corporation. All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
* CYPRESS PROVIDES THIS SOFTWARE "AS IS" AND MAKES NO WARRANTY
* OF ANY KIND, EXPRESS OR IMPLIED, WITH REGARD TO THIS SOFTWARE,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
* MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
* PURPOSE.
*******************************************************************************/

/******************************************************************************/
/* Include files                                                              */
/******************************************************************************/
#include "pdl_header.h"
#include <inttypes.h>

/******************************************************************************/
/* Local pre-processor symbols/macros ('#define')                             */
/******************************************************************************/

/* FRT */
#define  USER_MFT_FRT_UNIT      MFT0_FRT  
/*******************************************************************************
* define Mft Frt Channel 
*******************************************************************************/
#define  USER_MFT_FRT_CH        MFT_FRT_CH2

/*******************************************************************************
* define Mft Frt cycle value 
*******************************************************************************/
#define  USER_FRT_CYCLE_VAL     0xFFFF
#define  USER_FRT_MODE          FrtUpCount  

/* ICU */
#define  USER_MFT_ICU_UNIT       MFT0_ICU 

/*******************************************************************************
* define Mft Frt Channel 
*******************************************************************************/
#define  USER_MFT_ICU_CH         MFT_ICU_CH2

/* ICU IO */
/* Initialize P34 */
#define InitWaveGenIo()    Gpio1pin_InitOut(GPIO1PIN_P34, Gpio1pin_InitVal(0u))
#define WaveGenIoOut(v)    Gpio1pin_Put(GPIO1PIN_P34, v)     

#define SetPinFunc_ICxx()  SetPinFunc_IC02_0(0)

/******************************************************************************/
/* Local variable definitions ('static')                                      */
/******************************************************************************/
/*******************************************************************************
* Mft Frt Peak Interrupt count value 
*******************************************************************************/
static uint32_t m_u32CntFrtPeakIntTrg;
/*******************************************************************************
* Mft Icu Interrupt count value 
*******************************************************************************/
volatile static uint32_t m_u32CntIcuIntTrg;
/*******************************************************************************
* Mft Icu captured rising edge number 
*******************************************************************************/
volatile static uint32_t m_u32CntRisingEdgeTrg;
/*******************************************************************************
* Mft Icu captured falling edge number 
*******************************************************************************/
volatile static uint32_t m_u32CntFallingEdgeTrg;
/*******************************************************************************
* Mft Icu captured edge type buffer 
*******************************************************************************/
volatile static uint8_t m_au8EdgeTypeBuf[50];
/*******************************************************************************
* Mft Icu captured data value buffer 
*******************************************************************************/
volatile static uint32_t m_au32CapDataValBuf[50];
/*******************************************************************************
* Mft Icu captured edge number 
*******************************************************************************/
volatile static uint16_t m_u16CntCapEdgeNum;
volatile static uint8_t m_u8IoStatus = 0xFF;

static void MftFrtPeakIntHandler(void);
static void MftIcuIntHandler(void);
#ifdef DEBUG_PRINT
static void MftIcuDebugPrint(void);
#endif
static void MftIcuResetParam(void);
static void PollingWaveGenIo(void);

static void Delay(void);

/*******************************************************************************
* \brief Mft Icu example code
*
* 1. Set GPIO function to Icu
* 2. Configure Frt&Icu parameter
* 3. Enable Icu interrupt
* 4. Start Frt&Icu operation
* 5. Stop  Frt&Icu operation, disable interrupt
* 6. print Icu detected information
*******************************************************************************/

/*******************************************************************************
* Function Name: main
********************************************************************************
* Main function of project for FM family.
*
* \return int return value, if needed
*******************************************************************************/
int main(void)
{
    stc_mft_frt_config_t stcFrtConfig;
    stc_frt_irq_sel_t stcFrtIrqSel;
    stc_frt_irq_cb_t stcFrtIrqCallBack;

    /* Clear structures */
    PDL_ZERO_STRUCT(stcFrtConfig);
    PDL_ZERO_STRUCT(stcFrtIrqSel);
    PDL_ZERO_STRUCT(stcFrtIrqCallBack);
      
#ifdef DEBUG_PRINT	
    Uart_Io_Init();
#endif
	
    /* Initialize Gpio to generate the pulse which inputs to ICU */
    InitWaveGenIo();
   
    /* Configure the FRT parameter */
    stcFrtConfig.enFrtMode = USER_FRT_MODE;
    stcFrtConfig.enFrtClockDiv = FrtPclkDiv256;
    stcFrtConfig.bEnExtClock = FALSE;
    stcFrtConfig.bEnBuffer = TRUE;
    stcFrtConfig.pstcIrqCb = &stcFrtIrqCallBack;
    stcFrtConfig.pstcIrqEn = &stcFrtIrqSel;
    stcFrtConfig.bTouchNvic = TRUE;

    /* Configure frt interrupt mode */
    stcFrtIrqSel.bFrtPeakMatchIrq = TRUE; /* enable peak match interrupt */
    stcFrtIrqCallBack.pfnFrtPeakIrqCb = MftFrtPeakIntHandler;
    
    /* Initialize FRT */
    Mft_Frt_Init(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH, &stcFrtConfig);
    
    /* Set Frt count cycle */
    Mft_Frt_SetCountCycle(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH, USER_FRT_CYCLE_VAL);
    
#ifdef DEBUG_PRINT 
    printf("==================================================\n");
    printf("Mft Icu Interrupt Example Program Start \n");
    printf("==================================================\n");
#endif

    /* Initialize ICU function pins */
    SetPinFunc_ICxx(); 
    /* Select Frt channel */
    Mft_Icu_SelFrt(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH, (en_mft_icu_frt_t)USER_MFT_FRT_CH);
    /* Disable Icu operation */
    Mft_Icu_ConfigDetectMode(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH, IcuDisable);
    /* Enable Interrupt */
    Mft_Icu_EnableIrq(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH, MftIcuIntHandler, TRUE);

    /* Initialize trig counters */
    MftIcuResetParam();

#ifdef  DEBUG_PRINT
    printf("==================================================\n");
    printf("Icu Channel %d: Start\n", USER_MFT_ICU_CH);
    printf("Enable  Mft Icu Rising Edge Detection\n");
#endif
    /* Start Icu operation, Set detecting rising edge mode */
    Mft_Icu_ConfigDetectMode(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH, IcuRisingDetect);  

    /* Start Frt operation */
    Mft_Frt_Start(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH);
    Delay();

    while(m_u32CntIcuIntTrg < 10)
    {
        PollingWaveGenIo();
        Delay();
    }

    /* Stop FRT */
    Mft_Frt_Stop(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH);    
    Mft_Frt_SetCountVal(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH, 0x0000);
    /* Disable Mft Icu Operation and set mode to IcuDisable */
    Mft_Icu_ConfigDetectMode(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH,IcuDisable);

#ifdef DEBUG_PRINT
    printf("==================================================\n");
    printf("Disable Mft Icu Rising Edge Detection\n");
    printf("==================================================\n");
    MftIcuDebugPrint();
#endif
    /* Clear print counter buffer and related variables */
    MftIcuResetParam();
    
/********************************************************************/
#ifdef  DEBUG_PRINT
    printf("==================================================\n");
    printf("Enable  Mft Icu Falling Edge Detection\n");
#endif
    /* Start Icu operation, Set detecting falling edge mode */
    Mft_Icu_ConfigDetectMode(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH, IcuFallingDetect);  

    /* Start Frt operation */
    Mft_Frt_Start(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH);
    Delay();

    while(m_u32CntIcuIntTrg < 10)
    {
        PollingWaveGenIo();
        Delay();
    }

    /* Stop FRT */
    Mft_Frt_Stop(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH);    
    Mft_Frt_SetCountVal(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH, 0x0000);
    /* Disable Mft Icu Operation and set mode to IcuDisable */
    Mft_Icu_ConfigDetectMode(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH,IcuDisable);

#ifdef DEBUG_PRINT
    printf("==================================================\n");
    printf("Disable Mft Icu Falling Edge Detection\n");
    printf("==================================================\n");
    MftIcuDebugPrint();    
#endif
    /* Clear print counter buffer and related variables */
    MftIcuResetParam();
    
/********************************************************************/
#ifdef  DEBUG_PRINT
    printf("==================================================\n");
    printf("Enable  Mft Icu Both Edge Detection\n");
#endif
    
    /* Start Icu operation, Set detecting both edge mode */
    Mft_Icu_ConfigDetectMode(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH, IcuBothDetect);  

    /* Start Frt operation */
    Mft_Frt_Start(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH);
    Delay();

    while(m_u32CntIcuIntTrg < 10)
    {
        PollingWaveGenIo();
        Delay();
    }

    /* Stop FRT */
    Mft_Frt_Stop(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH);    
    Mft_Frt_SetCountVal(&USER_MFT_FRT_UNIT, USER_MFT_FRT_CH, 0x0000);
    /* Disable Mft Icu Operation and set mode to IcuDisable */
    Mft_Icu_ConfigDetectMode(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH,IcuDisable);
    

#ifdef DEBUG_PRINT
    printf("==================================================\n");
    printf("Disable Mft Icu Both Edge Detection\n");
    printf("==================================================\n");
    MftIcuDebugPrint();    
#endif
    MftIcuResetParam();

#ifdef DEBUG_PRINT
    printf("==================================================\n");
    printf("Icu Channel %d: Example Program End \n", USER_MFT_ICU_CH);
    printf("==================================================\n\n\n");
#endif

    while(1)
    {
    }
    
}

/*******************************************************************************
* Function Name: MftIcuIntHandler
********************************************************************************
* Mft Icu trigger interrupt handler
*******************************************************************************/
static void MftIcuIntHandler(void)
{
    m_u32CntIcuIntTrg++;

    m_au8EdgeTypeBuf[m_u16CntCapEdgeNum] = Mft_Icu_GetLastEdge(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH);
    /* 
    This is just a demo
    if absolute captured data value is needed
    please add Frt counter value: m_u32CntFrtPeakIntTrg*65536 
    */
    m_au32CapDataValBuf[m_u16CntCapEdgeNum] = Mft_Icu_GetCaptureData(&USER_MFT_ICU_UNIT, USER_MFT_ICU_CH)
                                                    + m_u32CntFrtPeakIntTrg * 0xFFFF;
    
    if(IcuFallingEdge == m_au8EdgeTypeBuf[m_u16CntCapEdgeNum])
    {
        m_u32CntFallingEdgeTrg++;
    }
    else if(IcuRisingEdge == m_au8EdgeTypeBuf[m_u16CntCapEdgeNum])
    {
        m_u32CntRisingEdgeTrg++;
    }
    m_u16CntCapEdgeNum++;

    return;
}

/*******************************************************************************
* Function Name: MftFrtPeakIntHandler
********************************************************************************
* Mft Frt callback function
*******************************************************************************/
static void MftFrtPeakIntHandler(void)
{
    m_u32CntFrtPeakIntTrg++;

    return;    
}

#ifdef DEBUG_PRINT

/*******************************************************************************
* Function Name: MftIcuDebugPrint
********************************************************************************
* Print debug information
*******************************************************************************/
static void MftIcuDebugPrint(void)
{
    uint16_t u16CntPrint;
    
    printf("Interrupt request times:      %"PRIu32"\n", m_u32CntIcuIntTrg);
    printf("Mft Icu Rising  Edge trigger: %"PRIu32"\n", m_u32CntRisingEdgeTrg);
    printf("Mft Icu Falling Edge trigger: %"PRIu32"\n", m_u32CntFallingEdgeTrg);
    for(u16CntPrint = 0; u16CntPrint < 10; u16CntPrint++)
    {
        printf("Captured Edge Type : %"PRIu8"\n", m_au8EdgeTypeBuf[u16CntPrint]);
        printf("Captured Data Value: %"PRIu32"\n", m_au32CapDataValBuf[u16CntPrint]);
    }

    return;
}
#endif

/*******************************************************************************
* Function Name: MftIcuResetParam
********************************************************************************
* Reset Mft Icu parameter values
*******************************************************************************/
static void MftIcuResetParam(void)
{
    uint16_t u16CntPrint;
    /* Clear print counter buffer and related variables */
    for(u16CntPrint = 0; u16CntPrint < 10; u16CntPrint++)
    {
        m_au8EdgeTypeBuf[u16CntPrint] = 0;
    }
    
    m_u32CntIcuIntTrg = 0;
    m_u16CntCapEdgeNum = 0;
    m_u16CntCapEdgeNum = 0;
    m_u32CntRisingEdgeTrg  = 0;
    m_u32CntFallingEdgeTrg = 0;
    m_u32CntFrtPeakIntTrg = 0;

    return;
}

/*******************************************************************************
* Function Name: PollingWaveGenIo
********************************************************************************
* Polling a GPIO for ICU input
*******************************************************************************/
static void PollingWaveGenIo(void)
{
    m_u8IoStatus = ~m_u8IoStatus;     
    WaveGenIoOut(m_u8IoStatus);

    return;
}

/*******************************************************************************
* Function Name: PollingWaveGenIo
********************************************************************************
* Time delay function
*******************************************************************************/
static void Delay(void)
{
    uint32_t u32Cnt = SystemCoreClock/4000;
    while (0 != (u32Cnt--));

    return;
}


/* [] END OF FILE */
